apiVersion: v1
kind: Service
metadata:
  name: sample-web-app-service  # Name of the service
spec:
  selector:
    app: sample-web-app  # Matches pods labeled with this app
  ports:
    - protocol: TCP
      port: 80  # Port exposed to the outside world
      targetPort: 8080  # Internal container port for the application
  type: LoadBalancer  # Expose the service via a cloud load balancer