apiVersion: v1
kind: Service
metadata:
  name: sample-web-app-service
spec:
  selector:
    app: sample-web-app
  ports:
    - protocol: TCP
      port: 80  # Port exposed on the LoadBalancer
      targetPort: 8080  # Port where the application is running in the container
  type: LoadBalancer