- name: Build Docker image
  docker_image:
    name: sample-web-app  # Name of the Docker image (this is not the Dockerfile name, but the image name)
    tag: latest           # Tag for the Docker image (e.g., 'latest')
    source: build
    build:           # Tells Docker to build the image
      path: ../app/         # Path to the directory containing the Dockerfile (relative to where the playbook is running)
  register: docker_build_result  # Registers the result of the build process for later use


- name: Fail if Docker build fails
  fail:
    msg: "Docker build failed with error: {{ docker_build_result.stderr }}"
  when: docker_build_result.failed

- name: Push Docker image to Docker Hub
  docker_image:
    name: docker.io/jazwii/sample-web-app
    tag: latest
    push: true
    source: build
  register: docker_push_result

- name: Fail if Docker push fails
  fail:
    msg: "Docker push failed with error: {{ docker_push_result.stderr }}"
  when: docker_push_result.failed
