- name: Build Docker image
  community.docker.docker_image:
    name: Dockerfile
    tag: latest
    build: true
    path: ../app/
  register: docker_build_result

- name: Fail if Docker build fails
  fail:
    msg: "Docker build failed with error: {{ docker_build_result.stderr }}"
  when: docker_build_result.failed

- name: Push Docker image to Docker Hub
  community.docker.docker_image:
    name: docker.io/jazwii/sample-web-app
    tag: latest
    push: true
    source: build
  register: docker_push_result

- name: Fail if Docker push fails
  fail:
    msg: "Docker push failed with error: {{ docker_push_result.stderr }}"
  when: docker_push_result.failed
