- name: Apply Kubernetes Deployment
  shell: kubectl apply -f ../k8s/deployment.yaml
  args:
    chdir: ../k8s

- name: Apply Kubernetes Service
  shell: kubectl apply -f ../k8s/service.yaml
  args:
    chdir: ../k8s