- name: Apply Kubernetes Deployment
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '../k8s/deployment.yaml') }}"
  register: deployment_result

- name: Fail if Kubernetes deployment fails
  fail:
    msg: "Kubernetes deployment failed with error: {{ deployment_result.stderr }}"
  when: deployment_result.failed

- name: Apply Kubernetes Service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '../k8s/service.yaml') }}"
  when: deployment_result.ok
